Вёрстка. Седона.
htmlacademy-htmlcss/2372605-sedona-37 pull request #2
Opened 2023-05-25 20:21 UTC by thirdSixPaths

2023-05-30 08:18 UTC, DoberBober commented on index.html
> +      <article class="modules-title Sedona-advantages">
```suggestion
      <article class="modules-title sedona-advantages">
```

2023-05-30 08:19 UTC, DoberBober commented on index.html
> +      <article class="modules-title Sedona-pluses">
```suggestion
      <article class="modules-title sedona-pluses">
```

2023-05-30 08:21 UTC, DoberBober commented on index.html
> +          <li class="suggestions-item-housing">
```suggestion
          <li class="suggestions-item suggestions-item-housing">
```

2023-05-30 08:24 UTC, DoberBober commented on index.html
> +      </section>
```suggestion
        <a class="footer-contacts-address-phone" href="tel:+78128121212">
          +7 (812) 812-12-12
        </a>
        
        <a class="html-academy-logo" href="#">
          <img class="logo" src="#" alt="Логотип HTML Academy.">
        </a>
```

2023-05-30 08:26 UTC, DoberBober commented on catalog.html
> +		  <header class="inner-header">
header и section обернуть в див/секшн.

2023-05-30 08:28 UTC, DoberBober commented on catalog.html
> +				  <button class="button">Сбросить</button>
```suggestion
				  <button class="submit">Применить</button>
				  <button class="reset">Сбросить</button>
```

2023-05-30 08:30 UTC, DoberBober commented on catalog.html
> +			  <select class="select-control" aria-label="Сортировка">
```suggestion
			  <select class="select-control" aria-label="Сортировка.">
```

2023-05-30 08:31 UTC, DoberBober commented on catalog.html
> +			  </a>
Объединить в див/списком.

2023-05-30 08:32 UTC, DoberBober commented on catalog.html
> +						  <img class="hotel-card-image" src="" alt="">
```suggestion
					  <a class="hotel-card-link" href="#">
						  <img class="hotel-card-image" src="" alt="">
					  </a>
```

2023-05-30 08:33 UTC, DoberBober commented on catalog.html
> +						  <img src="#" alt="Рейтинг отеля">
Местами поменять.

2023-05-30 08:35 UTC, DoberBober commented on catalog.html
> +				    ...
```suggestion
				    <li>...</li>
```

2023-05-30 08:38 UTC, DoberBober commented on catalog.html
> +			    <input class="email-field" type="email" name="user-email" id="user-email" placeholder="Ваш e-mail">
1. Label с visually-hidden.
2. aria-label="Введите ваш email.".

2023-05-30 08:40 UTC, DoberBober requested changes
.

2023-05-30 08:55 UTC, thirdSixPaths commented on index.html
> +      <article class="modules-title Sedona-advantages">
+

2023-06-03 08:17 UTC, DoberBober approved these changes
lgtm.

2023-06-03 08:18 UTC, merged